# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: structures.proto
# Protobuf Python Version: 6.30.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '-rc2',
    'structures.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10structures.proto\"a\n\nRpcRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\x12\x1c\n\x06params\x18\x04 \x03(\x0b\x32\x0c.BinaryValue\"W\n\x0bRpcResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\texception\x18\x02 \x01(\x0b\x32\n.Exception\x12\x1d\n\x07returns\x18\x03 \x01(\x0b\x32\x0c.BinaryValue\"\x15\n\x06String\x12\x0b\n\x03msg\x18\x01 \x01(\t\"1\n\x0fResponseMessage\x12\x1e\n\x08response\x18\x01 \x01(\x0b\x32\x0c.RpcResponse\"9\n\x0b\x42inaryValue\x12\x0e\n\x06isNull\x18\x01 \x01(\x08\x12\r\n\x05\x61rray\x18\x02 \x03(\x0c\x12\x0b\n\x03one\x18\x03 \x01(\x0c\"0\n\tException\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstackTrace\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'structures_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPCREQUEST']._serialized_start=20
  _globals['_RPCREQUEST']._serialized_end=117
  _globals['_RPCRESPONSE']._serialized_start=119
  _globals['_RPCRESPONSE']._serialized_end=206
  _globals['_STRING']._serialized_start=208
  _globals['_STRING']._serialized_end=229
  _globals['_RESPONSEMESSAGE']._serialized_start=231
  _globals['_RESPONSEMESSAGE']._serialized_end=280
  _globals['_BINARYVALUE']._serialized_start=282
  _globals['_BINARYVALUE']._serialized_end=339
  _globals['_EXCEPTION']._serialized_start=341
  _globals['_EXCEPTION']._serialized_end=389
# @@protoc_insertion_point(module_scope)
